import { Router, Request, Response } from 'express';
import { LocalLlmManager } from '../llm/LocalLlmManager.ts'; // Ensured strict TS extension

const router = Router();
const llmManager = new LocalLlmManager();

router.post('/optimize-prompt', async (req: Request, res: Response): Promise<void> => {
  try {
    const { 
      activeWorkflow, 
      dogBreed, 
      dogColor, 
      youtubeChannelName, 
      backgroundPhotoDescription 
    } = req.body;

    const breed = dogBreed || "Whippet";
    const color = dogColor || "pure white";
    const channelName = youtubeChannelName || "THE WHIPPET";
    const photoDesc = backgroundPhotoDescription || "a beautiful woman with long dark hair looking forward";

    // Detect if we are using Flux or SDXL to configure layout density
    const isFlux = String(activeWorkflow).includes('flux');

    // Build a specialized structural system instruction for your running Qwen engine
    const systemPrompt = `You are an expert AI prompt engineer optimizing descriptions for local image generation models. Your output must be highly scannable, detailed, and directly optimized for either Flux text compliance or SDXL layered composition.`;
    
    const userPrompt = `Generate a cinematic, highly detailed image generation prompt following these conditions:
    1. Primary subject: A 3D Pixar-style animated anthropomorphic ${breed} dog with ${color} fur sitting at a wooden gaming desk, paws on a mechanical RGB keyboard.
    2. Monitor screen detail: Must explicitly display a dark-mode YouTube channel layout showing video grids and the clear channel name text "${channelName}".
    3. Background asset: On the far-left wall partition, a framed realistic photograph portrait of a real woman, specifically described as: "${photoDesc}".
    4. Lighting: Cozy room environment, ambient neon LED light strips on the wall corners, volumetric studio illumination, highly detailed 3D octane render style.
    
    Provide your output as a single descriptive paragraph maximizing keyword coordinates. Do not include introductory text or meta commentary, respond with only the raw prompt string text.`;

    // Reach directly into your active running local LLM chat thread pool!
    const llmResponse = await llmManager.chat([
      { role: 'system', content: systemPrompt },
      { role: 'user', content: userPrompt }
    ], { temperature: 0.3, maxTokens: 400 });

    // Extract the raw text generated by your Qwen 2.5-VL engine
    const finalizedPromptText = llmResponse?.choices?.[0]?.message?.content || "";

    if (!finalizedPromptText.trim()) {
      throw new Error("Local LLM engine returned an empty prompt structure.");
    }

    // Adapt output formatting seamlessly to support your frontend workflow routes
    if (isFlux) {
      res.status(200).json({
        success: true,
        prompt: finalizedPromptText.trim()
      });
    } else {
      // SDXL requires a multi-pass structure. We feed the full scene into layer 1
      res.status(200).json({
        success: true,
        prompt: [
          finalizedPromptText.trim(),
          `A sharp, highly legible dark-mode YouTube channel webpage layout interface on a glass monitor, video layout thumbnails, crisp bold text that reads "${channelName}", clean UI graphic design layout.`,
          `A highly detailed, realistic framed photograph profile of a real person, specifically ${photoDesc}, sharp facial features, authentic portrait photography, studio lighting.`
        ]
      });
    }

  } catch (error: any) {
    console.error('[API Router Failure]:', error);
    res.status(500).json({ 
      success: false, 
      error: error?.message || 'Failed to communicate with local LLM chat runtime.' 
    });
  }
});

export default router;
