import fs from 'fs/promises';
import path from 'path';
import { spawn, execFile } from 'child_process';
import { promisify } from 'util';

const execFileAsync = promisify(execFile);
export type GinaBootMode = 'dashboard-only' | 'dashboard-comfy' | 'factory' | 'manual';
export interface ManagedTerminal { id:string; pid:number; title:string; relativePath:string; startedAt:string; alive:boolean; }
const ALLOWED_BOOT_MODES = new Set<GinaBootMode>(['dashboard-only','dashboard-comfy','factory','manual']);

export class DevelopmentModeService {
  private readonly root:string;
  private readonly managed = new Map<string,{pid:number;title:string;relativePath:string;startedAt:string}>();
  constructor(root = process.env.GINA_ROOT || (process.platform === 'win32' ? 'C:\\Gina_AI' : process.cwd())) { this.root = path.resolve(root); }
  getBootMode():GinaBootMode { const value=String(process.env.GINA_BOOT_MODE||'').toLowerCase() as GinaBootMode; return ALLOWED_BOOT_MODES.has(value)?value:'factory'; }
  isDevelopmentMode(){ return process.env.GINA_DEV_MODE === '1' || this.getBootMode() !== 'factory'; }
  private allowedDirs(){ return [this.root,path.join(this.root,'scripts')]; }
  private isAllowedBatchPath(candidate:string){ const resolved=path.resolve(candidate); if(path.extname(resolved).toLowerCase()!=='.bat') return false; return this.allowedDirs().some(dir=>{const rel=path.relative(path.resolve(dir),resolved); return rel && rel!=='..' && !rel.startsWith('..'+path.sep) && !path.isAbsolute(rel);}); }
  async listStartupBats(){ const found=new Set<string>(); for(const dir of this.allowedDirs()){ try{ const entries=await fs.readdir(dir,{withFileTypes:true}); for(const entry of entries){ if(!entry.isFile()||!entry.name.toLowerCase().endsWith('.bat')) continue; const full=path.join(dir,entry.name); if(this.isAllowedBatchPath(full)) found.add(path.relative(this.root,full).replaceAll(path.sep,'/')); } }catch{} } return [...found].sort().map(relativePath=>({relativePath,title:path.basename(relativePath,'.bat')})); }
  private remember(title:string,relativePath:string,child:ReturnType<typeof spawn>){ const id='terminal_'+Date.now()+'_'+Math.random().toString(36).slice(2,8); const record={pid:child.pid||-1,title,relativePath,startedAt:new Date().toISOString()}; this.managed.set(id,record); const forget=()=>this.managed.delete(id); child.once('exit',forget); child.once('error',forget); return id; }
  async runBatch(relativePath:string):Promise<ManagedTerminal>{ if(process.platform!=='win32') throw new Error('Startup BAT control is only available on Windows.'); const normalized=String(relativePath||'').replaceAll('/',path.sep); const full=path.resolve(this.root,normalized); if(!this.isAllowedBatchPath(full)) throw new Error("That startup script is outside Gina's approved BAT directories."); const relative=path.relative(this.root,full).replaceAll(path.sep,'/'); const title=path.basename(full,'.bat'); const child=spawn('cmd.exe',['/k','call',full],{cwd:this.root,windowsHide:false,stdio:'ignore'}); const id=this.remember(title,relative,child); return {id,pid:child.pid||-1,title,relativePath:relative,startedAt:new Date().toISOString(),alive:true}; }
  async terminate(id:string){ if(process.platform!=='win32') throw new Error('Process control is only available on Windows.'); const record=this.managed.get(id); if(!record) return {success:false,message:'Managed terminal was not found or has already exited.'}; try{ await execFileAsync('taskkill.exe',['/PID',String(record.pid),'/T','/F'],{windowsHide:true,timeout:10000}); }catch(error:any){ const message=String(error?.stderr||error?.message||''); if(!/not found|no running instance|does not exist/i.test(message)) throw new Error('Failed to terminate managed terminal: '+message); } finally { this.managed.delete(id); } return {success:true,message:'Terminated '+record.title+' (PID '+record.pid+') and its child process tree.'}; }
  async closeTerminals(){ const ids=[...this.managed.keys()]; const failures:string[]=[]; for(const id of ids){ try{const r=await this.terminate(id); if(!r.success) failures.push(r.message);}catch(error:any){failures.push(error?.message||String(error));} } return {success:failures.length===0,closed:ids.length-failures.length,failures}; }
  async getState(){ const terminals:ManagedTerminal[]=[]; for(const [id,record] of this.managed.entries()){ let alive=true; if(process.platform==='win32'){ try{await execFileAsync('tasklist.exe',['/FI','PID eq '+record.pid,'/FO','CSV','/NH'],{windowsHide:true,timeout:3000});}catch{alive=false;} } if(!alive){this.managed.delete(id);continue;} terminals.push({id,pid:record.pid,title:record.title,relativePath:record.relativePath,startedAt:record.startedAt,alive}); } const cold=this.getBootMode()==='dashboard-only'||this.getBootMode()==='manual'; return {developmentMode:this.isDevelopmentMode(),bootMode:this.getBootMode(),platform:process.platform,dashboardOnly:cold,heavyInitialization:!cold,terminals}; }
  async restart(mode:GinaBootMode){ if(!ALLOWED_BOOT_MODES.has(mode)) throw new Error('Unsupported Gina boot mode: '+mode); if(process.platform!=='win32') throw new Error('Development restart control is currently implemented for Windows only.'); const launcher=path.join(this.root,'Start_Gina_Development.bat'); if(mode==='factory'){ const factory=path.join(this.root,'Start_Factory.bat'); if(!(await fs.stat(factory).catch(()=>null))?.isFile()) throw new Error('Missing '+factory); const child=spawn('cmd.exe',['/k','call',factory],{cwd:this.root,windowsHide:false,stdio:'ignore'}); this.remember('Start_Factory','Start_Factory.bat',child); } else { if(!(await fs.stat(launcher).catch(()=>null))?.isFile()) throw new Error('Missing '+launcher); const child=spawn('cmd.exe',['/k','call',launcher,mode],{cwd:this.root,windowsHide:false,stdio:'ignore'}); this.remember('Gina '+mode,'Start_Gina_Development.bat',child); } setTimeout(()=>process.exit(0),750); return {ok:true,restarting:true,mode}; }
}