import React,{useCallback,useEffect,useState} from 'react';
import {Power,RefreshCw,Square,Terminal,Wrench,XCircle} from 'lucide-react';
type BootMode='dashboard-only'|'dashboard-comfy'|'factory'|'manual';
interface TerminalRow{id:string;pid:number;title:string;relativePath:string;startedAt:string;alive:boolean}
interface DevState{developmentMode:boolean;bootMode:BootMode;platform:string;dashboardOnly:boolean;heavyInitialization:boolean;terminals:TerminalRow[]}
interface BatRow{relativePath:string;title:string}
const MODES:Array<{id:BootMode;label:string;detail:string}>= [
 {id:'dashboard-only',label:'Dashboard Only',detail:'Gina UI/API only. No ComfyUI orchestration, AIDA startup or knowledge reindex.'},
 {id:'dashboard-comfy',label:'Dashboard + ComfyUI',detail:'Open Gina immediately while ComfyUI starts separately.'},
 {id:'manual',label:'Manual / Cold',detail:'Keep automatic background services off; start individual BATs yourself.'},
 {id:'factory',label:'Full Factory',detail:'Use the normal Start_Factory.bat startup sequence.'}
];
export const DevelopmentModePanel:React.FC=()=>{
 const [state,setState]=useState<DevState|null>(null); const [bats,setBats]=useState<BatRow[]>([]); const [selectedMode,setSelectedMode]=useState<BootMode>('dashboard-only'); const [busy,setBusy]=useState<string|null>(null); const [message,setMessage]=useState('');
 const load=useCallback(async()=>{try{const [a,b]=await Promise.all([fetch('/api/dev/state',{cache:'no-store'}),fetch('/api/dev/startups',{cache:'no-store'})]);const s=await a.json();const x=await b.json();if(a.ok){setState(s);setSelectedMode(s.bootMode||'dashboard-only')}if(b.ok)setBats(Array.isArray(x.startups)?x.startups:[])}catch(e:any){setMessage(e?.message||'Development Mode API unavailable.')}},[]);
 useEffect(()=>{void load();const t=setInterval(()=>void load(),3000);return()=>clearInterval(t)},[load]);
 const post=async(url:string,body?:any)=>{setBusy(url);setMessage('');try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'HTTP '+r.status);setMessage(d.message||(d.restarting?'Restarting Gina in '+selectedMode+' mode...':'Command completed.'));await load()}catch(e:any){setMessage(e?.message||'Command failed.')}finally{setBusy(null)}};
 return <section className="min-h-[calc(100vh-180px)] bg-slate-950 text-slate-200 border border-slate-800 rounded-xl overflow-hidden">
  <header className="flex flex-col lg:flex-row lg:items-center justify-between gap-4 px-5 py-4 border-b border-slate-800"><div><div className="flex items-center gap-2 text-emerald-400 text-[10px] font-bold tracking-[0.25em] uppercase"><Wrench className="w-4 h-4"/> Development Mode</div><h1 className="text-xl font-semibold text-slate-100 mt-1">Boot & Process Control</h1><p className="text-xs text-slate-500 mt-1">Open Gina without waiting for heavy ML weights, model caches or database/index initialization.</p></div><div className="flex items-center gap-2 text-[10px] font-mono"><span className="px-2 py-1 rounded border border-emerald-500/30 bg-emerald-500/10 text-emerald-300">MODE: {state?.bootMode||'loading'}</span><button type="button" onClick={()=>void load()} className="p-2 rounded border border-slate-700 hover:border-slate-500" title="Refresh"><RefreshCw className="w-3.5 h-3.5"/></button></div></header>
  <div className="grid xl:grid-cols-[minmax(0,1fr)_minmax(360px,0.8fr)]"><div className="p-5 space-y-5 border-r border-slate-800">
   <div><div className="text-[10px] uppercase tracking-widest text-slate-500 mb-2">Boot mode</div><div className="grid md:grid-cols-2 gap-2">{MODES.map(mode=><button key={mode.id} type="button" onClick={()=>setSelectedMode(mode.id)} className={'text-left p-3 rounded-lg border transition-colors '+(selectedMode===mode.id?'border-emerald-500/60 bg-emerald-500/10':'border-slate-800 bg-slate-900/40 hover:border-slate-700')}><div className="flex items-center justify-between"><span className="text-xs font-bold text-slate-200">{mode.label}</span>{selectedMode===mode.id&&<Power className="w-3.5 h-3.5 text-emerald-400"/>}</div><p className="text-[10px] text-slate-500 mt-1 leading-relaxed">{mode.detail}</p></button>)}</div></div>
   <div className="flex flex-wrap gap-2"><button type="button" disabled={busy!==null} onClick={()=>void post('/api/dev/restart',{mode:selectedMode})} className="px-3 py-2 rounded bg-emerald-500 text-slate-950 text-[10px] font-bold uppercase flex items-center gap-2 disabled:opacity-50"><RefreshCw className="w-3.5 h-3.5"/> Restart in Selected Mode</button><button type="button" disabled={busy!==null} onClick={()=>void post('/api/dev/close-terminals')} className="px-3 py-2 rounded bg-rose-500/10 text-rose-300 border border-rose-500/30 text-[10px] font-bold uppercase flex items-center gap-2 disabled:opacity-50"><XCircle className="w-3.5 h-3.5"/> Close Managed Terminals</button></div>
   <div className="border-t border-slate-800 pt-4"><div className="flex items-center justify-between mb-2"><div className="text-[10px] uppercase tracking-widest text-slate-500">Runtime state</div><span className={state?.heavyInitialization?'text-amber-300':'text-emerald-300'}>{state?.heavyInitialization?'HEAVY BOOT ENABLED':'COLD / LIGHT BOOT'}</span></div><pre className="text-[10px] leading-5 font-mono text-slate-400 whitespace-pre-wrap">{JSON.stringify({bootMode:state?.bootMode,developmentMode:state?.developmentMode,dashboardOnly:state?.dashboardOnly,platform:state?.platform},null,2)}</pre></div>
   {message&&<div className="text-[10px] font-mono text-slate-300 border border-slate-800 bg-slate-900/50 p-3 rounded">{message}</div>}
  </div><div className="p-5 space-y-5">
   <div><div className="text-[10px] uppercase tracking-widest text-slate-500 mb-2">Managed terminals</div>{state?.terminals?.length?<div className="space-y-2">{state.terminals.map(row=><div key={row.id} className="p-3 rounded-lg border border-slate-800 bg-slate-900/40"><div className="flex items-center justify-between gap-2"><div><div className="text-xs font-bold text-slate-200">{row.title}</div><div className="text-[9px] font-mono text-slate-500">PID {row.pid} · {row.relativePath}</div></div><button type="button" onClick={()=>void post('/api/dev/terminate',{id:row.id})} className="p-2 rounded border border-rose-500/30 text-rose-300 hover:bg-rose-500/10" title="Terminate"><Square className="w-3.5 h-3.5"/></button></div></div>)}</div>:<div className="text-[10px] text-slate-600">No Gina-managed terminals are currently tracked.</div>}</div>
   <div><div className="flex items-center justify-between mb-2"><div className="text-[10px] uppercase tracking-widest text-slate-500">Startup BATs</div><span className="text-[9px] font-mono text-slate-600">{bats.length} available</span></div><div className="space-y-1 max-h-[430px] overflow-auto">{bats.map(script=><div key={script.relativePath} className="flex items-center gap-2 p-2 rounded border border-slate-900 hover:border-slate-800"><Terminal className="w-3.5 h-3.5 text-slate-500 shrink-0"/><span className="text-[10px] font-mono text-slate-300 truncate flex-1" title={script.relativePath}>{script.relativePath}</span><button type="button" disabled={busy!==null} onClick={()=>void post('/api/dev/run-bat',{relativePath:script.relativePath})} className="px-2 py-1 rounded bg-slate-900 border border-slate-700 text-[9px] font-bold uppercase hover:border-emerald-500/50 disabled:opacity-50">Run</button></div>)}</div></div>
  </div></div></section>;
};