import React, { useEffect, useState } from 'react';
import { Brain, Search, RefreshCw, Archive, ShieldCheck } from 'lucide-react';

interface Entry { id:string; kind:string; title:string; content:string; source:string; confidence:string; verified:boolean; uses:number; updatedAt:string; }

export const KnowledgeBasePanel: React.FC<{ onAddLog?: (level:any, message:string)=>void }> = ({onAddLog}) => {
  const [entries,setEntries]=useState<Entry[]>([]); const [stats,setStats]=useState<any>(null); const [q,setQ]=useState(''); const [loading,setLoading]=useState(false);
  const load=async(query='')=>{setLoading(true);try{const [a,b]=await Promise.all([fetch(`/api/knowledge?limit=80${query?`&q=${encodeURIComponent(query)}`:''}`),fetch('/api/knowledge/status')]); if(a.ok)setEntries((await a.json()).entries||[]); if(b.ok)setStats((await b.json()).status||null);}catch(e:any){onAddLog?.('warn',`[Knowledge] ${e?.message||'Unable to load knowledge base'}`)}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const archive=async(id:string)=>{try{const r=await fetch('/api/knowledge/archive',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});if(r.ok){onAddLog?.('info','[Knowledge] Entry archived.');load(q)}}catch{}}
  return <div className="bg-slate-900/90 border border-slate-800 rounded-xl overflow-hidden shadow-lg">
    <div className="p-4 border-b border-slate-800 flex items-center justify-between gap-3">
      <div className="flex items-center gap-3"><div className="p-2 rounded-lg bg-violet-500/10 text-violet-300 border border-violet-500/20"><Brain className="w-5 h-5"/></div><div><div className="text-sm font-semibold text-slate-100">Persistent Learning Knowledge Base</div><div className="text-[11px] text-slate-400">Verified lessons and solutions stored locally. 0 MB VRAM.</div></div></div>
      <button onClick={()=>load(q)} disabled={loading} className="p-2 rounded-lg border border-slate-700 bg-slate-950 text-slate-300 hover:text-white"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/></button>
    </div>
    <div className="p-4 space-y-4">
      <div className="grid grid-cols-2 md:grid-cols-4 gap-2"><div className="bg-slate-950/60 rounded-lg border border-slate-800 p-2"><div className="text-[9px] text-slate-500 uppercase">Entries</div><div className="text-lg font-bold text-violet-300">{stats?.total||0}</div></div><div className="bg-slate-950/60 rounded-lg border border-slate-800 p-2"><div className="text-[9px] text-slate-500 uppercase">Verified</div><div className="text-lg font-bold text-emerald-300">{stats?.verified||0}</div></div><div className="bg-slate-950/60 rounded-lg border border-slate-800 p-2"><div className="text-[9px] text-slate-500 uppercase">Solutions</div><div className="text-lg font-bold text-cyan-300">{stats?.byKind?.solution||0}</div></div><div className="bg-slate-950/60 rounded-lg border border-slate-800 p-2"><div className="text-[9px] text-slate-500 uppercase">Lessons</div><div className="text-lg font-bold text-amber-300">{stats?.byKind?.lesson||0}</div></div></div>
      <div className="flex gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-500"/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load(q)} placeholder="Search what Gina has learned..." className="w-full bg-slate-950 border border-slate-700 rounded-lg pl-9 pr-3 py-2 text-xs text-slate-100"/></div><button onClick={()=>load(q)} className="px-3 rounded-lg bg-violet-600 hover:bg-violet-500 text-white text-xs font-semibold">Search</button></div>
      <div className="space-y-2 max-h-[420px] overflow-y-auto custom-scrollbar">{entries.length===0?<div className="text-xs text-slate-500 p-4 text-center">No learned knowledge yet. Successful verified agent work will populate this automatically.</div>:entries.map(e=><div key={e.id} className="border border-slate-800 bg-slate-950/50 rounded-lg p-3"><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-semibold text-slate-100">{e.title}</div><div className="flex items-center gap-2 mt-1 text-[9px] text-slate-500"><span>{e.kind}</span><span>·</span><span>{e.confidence}</span>{e.verified&&<><span>·</span><ShieldCheck className="w-3 h-3 text-emerald-400"/><span className="text-emerald-400">verified</span></>}</div></div><button onClick={()=>archive(e.id)} title="Archive knowledge" className="text-slate-600 hover:text-rose-300"><Archive className="w-3.5 h-3.5"/></button></div><p className="text-[11px] text-slate-400 mt-2 whitespace-pre-wrap">{e.content.slice(0,900)}</p><div className="text-[9px] text-slate-600 mt-2">Source: {e.source} · Used {e.uses}×</div></div>)}</div>
    </div>
  </div>
};
