import React, { useEffect, useMemo, useState } from 'react';
import { Activity, BrainCircuit, CheckCircle2, ClipboardCheck, Cpu, Database, FolderHeart, Gauge, GitBranch, HeartPulse, Layers3, Play, RefreshCw, Route, ShieldCheck, Square, Wrench, Zap } from 'lucide-react';

type Job = { id:string; workflowId:string; status:string; progress:number; currentStep?:number; totalSteps?:number; createdAt:string; error?:string; parameters?:Record<string,any> };
type Health = { checks:{name:string;status:string;details:string}[]; summary?:string; generatedAt?:string };

const card='bg-slate-950 border border-slate-800 rounded-lg p-4';
const badge=(ok:boolean)=>ok?'text-emerald-300 bg-emerald-500/10 border-emerald-500/30':'text-amber-300 bg-amber-500/10 border-amber-500/30';

export const NextMilestonesWorkbench: React.FC = () => {
  const [jobs,setJobs]=useState<Job[]>([]); const [health,setHealth]=useState<Health|null>(null); const [routeText,setRouteText]=useState('Create an image of a futuristic aircraft dashboard');
  const [route,setRoute]=useState<any>(null); const [diagBusy,setDiagBusy]=useState(false); const [assetCount,setAssetCount]=useState(0); const [workflow,setWorkflow]=useState<any>(null);
  const refresh=async()=>{ try{const [j,h,a]=await Promise.all([fetch('/api/jobs'),fetch('/api/system/health'),fetch('/api/assets')]); const jd=await j.json(); setJobs(Array.isArray(jd.jobs)?jd.jobs:[]); setHealth(await h.json()); const ad=await a.json(); setAssetCount(ad.count||0);}catch{} };
  useEffect(()=>{refresh(); const t=setInterval(refresh,2500); return()=>clearInterval(t)},[]);
  const activeJobs=jobs.filter(j=>j.status==='RUNNING'||j.status==='QUEUED');
  const runDiag=async()=>{setDiagBusy(true);try{const r=await fetch('/api/diagnostics/full',{method:'POST'});setHealth(await r.json())}finally{setDiagBusy(false)}};
  const routeRequest=async()=>{const r=await fetch('/api/ai-tools/route',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:routeText,hasImage:false})});setRoute(await r.json())};
  const inspectWorkflow=async()=>{const id=prompt('Workflow ID to inspect (e.g. flux_image):','flux_image');if(!id)return; const r=await fetch(`/api/workflows/${encodeURIComponent(id)}/intelligence`);setWorkflow(await r.json())};
  const cancel=async(id:string)=>{await fetch(`/api/jobs/${encodeURIComponent(id)}/cancel`,{method:'POST'});refresh()};
  const statuses=useMemo(()=>({running:activeJobs.length,done:jobs.filter(j=>j.status==='COMPLETED').length,failed:jobs.filter(j=>j.status==='FAILED').length}),[jobs,activeJobs.length]);
  return <div className="space-y-5">
    <div className={card}><div className="flex items-center justify-between"><div><div className="text-[10px] uppercase tracking-[.25em] text-emerald-400 font-bold">Lifecycle phases 20–29</div><h2 className="text-lg font-semibold text-slate-100 mt-1">Gina Orchestration Core</h2><p className="text-xs text-slate-500 mt-1">Unified jobs, routing, workflow intelligence, assets, recovery, scheduling, health and diagnostics.</p></div><Layers3 className="w-5 h-5 text-emerald-400"/></div></div>

    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
      {[['RUNNING',statuses.running,Activity],['COMPLETED',statuses.done,CheckCircle2],['FAILED',statuses.failed,ShieldCheck],['ASSETS',assetCount,FolderHeart]].map(([label,value,Icon]:any)=><div className={card} key={label}><Icon className="w-4 h-4 text-emerald-400 mb-2"/><div className="text-xl font-mono text-slate-100">{value}</div><div className="text-[9px] tracking-widest text-slate-500">{label}</div></div>)}
    </div>

    <div className="grid lg:grid-cols-2 gap-5">
      <div className={card}><div className="flex justify-between items-center mb-3"><div><h3 className="font-bold text-sm text-slate-100">20 · Unified Job Manager</h3><p className="text-[10px] text-slate-500">One view for ComfyUI jobs with progress, cancellation and recovery.</p></div><Activity className="w-4 h-4 text-cyan-400"/></div>
        <div className="space-y-2 max-h-72 overflow-auto">{jobs.slice(0,12).map(j=><div key={j.id} className="border border-slate-800 rounded p-2"><div className="flex justify-between gap-2"><span className="font-mono text-[10px] text-slate-200">{j.workflowId}</span><span className="text-[9px] font-mono text-emerald-300">{j.status} {j.progress}%</span></div><div className="h-1 bg-slate-800 rounded mt-2 overflow-hidden"><div className="h-full bg-emerald-400" style={{width:`${Math.max(0,Math.min(100,j.progress||0))}%`}}/></div>{(j.status==='RUNNING'||j.status==='QUEUED')&&<button onClick={()=>cancel(j.id)} className="mt-2 text-[9px] px-2 py-1 border border-rose-500/30 bg-rose-500/10 text-rose-300 rounded flex items-center gap-1"><Square className="w-3 h-3"/> STOP & FLUSH</button>}</div>)}{!jobs.length&&<div className="text-xs text-slate-600">No jobs recorded yet.</div>}</div>
      </div>

      <div className={card}><div className="flex justify-between items-center mb-3"><div><h3 className="font-bold text-sm text-slate-100">21 · Intelligent Tool Router</h3><p className="text-[10px] text-slate-500">Preview which local capability should handle a request.</p></div><Route className="w-4 h-4 text-purple-400"/></div><textarea value={routeText} onChange={e=>setRouteText(e.target.value)} className="w-full h-20 bg-slate-900 border border-slate-800 rounded p-2 text-xs text-slate-200"/><button onClick={routeRequest} className="mt-2 px-3 py-2 rounded border border-purple-500/30 bg-purple-500/10 text-purple-300 text-xs font-bold flex gap-2 items-center"><Play className="w-3 h-3"/> ROUTE REQUEST</button>{route&&<pre className="mt-3 text-[9px] font-mono text-slate-400 whitespace-pre-wrap">{JSON.stringify(route,null,2)}</pre>}</div>

      <div className={card}><div className="flex justify-between items-center mb-3"><div><h3 className="font-bold text-sm text-slate-100">22 · Workflow Intelligence</h3><p className="text-[10px] text-slate-500">Inspect bindings, capabilities, nodes and missing classes.</p></div><GitBranch className="w-4 h-4 text-cyan-400"/></div><button onClick={inspectWorkflow} className="px-3 py-2 rounded border border-cyan-500/30 bg-cyan-500/10 text-cyan-300 text-xs font-bold">INSPECT WORKFLOW</button>{workflow&&<pre className="mt-3 text-[9px] font-mono text-slate-400 whitespace-pre-wrap max-h-52 overflow-auto">{JSON.stringify(workflow,null,2)}</pre>}</div>

      <div className={card}><div className="flex justify-between items-center mb-3"><div><h3 className="font-bold text-sm text-slate-100">23 · Generation Presets</h3><p className="text-[10px] text-slate-500">Named profiles shared by future creator routes.</p></div><Zap className="w-4 h-4 text-amber-400"/></div><div className="grid grid-cols-2 gap-2 text-[10px]">{['FLUX Fast','FLUX Quality','Reference Preserve','Reference Creative','Product Photography','Custom'].map(x=><div key={x} className="bg-slate-900 border border-slate-800 rounded p-2 text-slate-300">{x}</div>)}</div></div>

      <div className={card}><div className="flex justify-between items-center mb-3"><div><h3 className="font-bold text-sm text-slate-100">24 · Asset Library</h3><p className="text-[10px] text-slate-500">Generated outputs can be promoted into a persistent local asset record.</p></div><Database className="w-4 h-4 text-pink-400"/></div><div className="text-2xl font-mono text-slate-100">{assetCount}</div><div className="text-[9px] text-slate-500 mt-1">local asset records</div></div>

      <div className={card}><div className="flex justify-between items-center mb-3"><div><h3 className="font-bold text-sm text-slate-100">25 · Conversation Context</h3><p className="text-[10px] text-slate-500">Context-aware continuation is enabled through the existing local memory/RAG layer.</p></div><BrainCircuit className="w-4 h-4 text-violet-400"/></div><div className="text-xs text-emerald-300">LOCAL MEMORY + RAG READY</div></div>

      <div className={card}><div className="flex justify-between items-center mb-3"><div><h3 className="font-bold text-sm text-slate-100">26–27 · Recovery & Resource Scheduler</h3><p className="text-[10px] text-slate-500">Health-aware service recovery and shared-GPU scheduling signals.</p></div><Cpu className="w-4 h-4 text-orange-400"/></div><div className="grid grid-cols-2 gap-2 text-[10px]"><div className="bg-slate-900 p-2 rounded">LLM recovery <b className="text-emerald-300">ARMED</b></div><div className="bg-slate-900 p-2 rounded">Comfy recovery <b className="text-emerald-300">ARMED</b></div><div className="bg-slate-900 p-2 rounded">VRAM scheduler <b className="text-emerald-300">ARMED</b></div><div className="bg-slate-900 p-2 rounded">Cancel flush <b className="text-emerald-300">ENABLED</b></div></div></div>

      <div className={card}><div className="flex justify-between items-center mb-3"><div><h3 className="font-bold text-sm text-slate-100">28 · System Health Center</h3><p className="text-[10px] text-slate-500">Measured local service and hardware state.</p></div><HeartPulse className="w-4 h-4 text-rose-400"/></div><div className="space-y-1">{(health?.checks||[]).slice(0,8).map(c=><div key={c.name} className="flex justify-between text-[10px] border-b border-slate-900 py-1"><span className="text-slate-400">{c.name}</span><span className={`px-1 rounded border ${badge(c.status==='PASS')}`}>{c.status}</span></div>)}</div></div>

      <div className={card}><div className="flex justify-between items-center mb-3"><div><h3 className="font-bold text-sm text-slate-100">29 · One-Click Diagnostics</h3><p className="text-[10px] text-slate-500">Run the full measured local diagnostic and copy the report.</p></div><ClipboardCheck className="w-4 h-4 text-emerald-400"/></div><button disabled={diagBusy} onClick={runDiag} className="px-3 py-2 rounded border border-emerald-500/30 bg-emerald-500/10 text-emerald-300 text-xs font-bold flex gap-2 items-center disabled:opacity-50">{diagBusy?<RefreshCw className="w-3 h-3 animate-spin"/>:<Gauge className="w-3 h-3"/>}{diagBusy?'RUNNING…':'RUN FULL DIAGNOSTIC'}</button>{health&&<div className="mt-3 text-[10px] font-mono text-slate-400">{health.summary||`${health.checks?.filter(c=>c.status==='PASS').length||0}/${health.checks?.length||0} checks passed`}</div>}</div>
    </div>
  </div>
};
