export const APP_VERSION = '1.18.2';
export const ACTIVE_SAVE_POINT_ID = 'RESTORE_V1.18.2_CREATE_STUDIO_FINALISATION';
export const ACTIVE_LIFECYCLE_PHASE = 36;
export const ACTIVE_LIFECYCLE_NAME = 'PHASE 36 — CREATE STUDIO FINALISATION & PERSISTENT EDIT QUEUE';
